version: '3'
services:
  node-denomailer:
    container_name: node-denomailer
    build: .
    restart: always
    dns:
      - 1.1.1.1
      - 9.9.9.9
    networks:
      - node-piotrkieltyka-website
    environment:
      ACME_CHALLENGE: ${acmeChallenge}
      EMAIL_USERNAME: ${emailUsername}
      EMAIL_RECIPIENT: ${emailRecipient}
      SERVICE_URL: ${service_url}
      SERVICE_ID: ${service_id}
      USER_ID: ${user_id}
      ACCESS_TOKEN: ${access_token}
      MAILSERVER_PORT: ${mailServerPort}
      MAILSERVER_SECRET: ${mailServerSecret}
      MAILSERVER_ORIGINS: ${mailServerOriginsAllowed}
    deploy:
      resources:
        limits:
          memory: 128m
networks:
  node-piotrkieltyka-website:
    name: node-piotrkieltyka-website
