version: '3'
services:
  denomailer:
    container_name: denomailer
    build: .
    restart: always
    networks:
      - node-piotrkieltyka-website
    ports:
      - '33032:33032'
    environment:
      EMAIL_USERNAME: ${emailUsername}
      EMAIL_PASSWORD: ${emailPassword}
      EMAIL_SERVER_URL: ${emailServerUrl}
      EMAIL_SERVER_PORT: ${emailServerPort}
      EMAIL_RECIPIENT: ${emailRecipient}
      MAILSERVER_PORT: ${mailServerPort}
      MAILSERVER_SECRET: ${mailServerSecret}
      MAILSERVER_ORIGINS: ${mailServerOriginsAllowed}
    deploy:
      resources:
        limits:
          memory: 128m
networks:
  node-piotrkieltyka-website:
    name: node-piotrkieltyka-website
